(ns advocado.mui
  (:require [cljsjs.material-ui]
            [tincture.core :refer [<sub]]
            [goog.object :as gobj]
            [reagent.core :as r])
  (:refer-clojure :exclude [List]))

(def StylesProvider (r/adapt-react-class (aget js/MaterialUIStyles "StylesProvider")))
(def MuiThemeProvider (r/adapt-react-class (aget js/MaterialUI "MuiThemeProvider")))
(def Grid (r/adapt-react-class (aget js/MaterialUI "Grid")))
(def Paper (r/adapt-react-class (aget js/MaterialUI "Paper")))
(def Button (r/adapt-react-class (aget js/MaterialUI "Button")))
(def TextField (r/adapt-react-class (aget js/MaterialUI "TextField")))
(def Typography (r/adapt-react-class (aget js/MaterialUI "Typography")))
(def SvgIcon (r/adapt-react-class (aget js/MaterialUI "SvgIcon")))
(def AppBar (r/adapt-react-class (aget js/MaterialUI "AppBar")))
(def Toolbar (r/adapt-react-class (aget js/MaterialUI "Toolbar")))
(def IconButton (r/adapt-react-class (aget js/MaterialUI "IconButton")))
(def Icon (r/adapt-react-class (aget js/MaterialUI "Icon")))
(def CircularProgress (r/adapt-react-class (aget js/MaterialUI "CircularProgress")))
(def Link (r/adapt-react-class (aget js/MaterialUI "Link")))
(def LinearProgress (r/adapt-react-class (aget js/MaterialUI "LinearProgress")))
(def FormControl (r/adapt-react-class (aget js/MaterialUI "FormControl")))
(def FormControlLabel (r/adapt-react-class (aget js/MaterialUI "FormControlLabel")))
(def Input (r/adapt-react-class (aget js/MaterialUI "Input")))
(def InputLabel (r/adapt-react-class (aget js/MaterialUI "InputLabel")))
(def FormHelperText (r/adapt-react-class (aget js/MaterialUI "FormHelperText")))
(def Select (r/adapt-react-class (aget js/MaterialUI "Select")))
(def MenuItem (r/adapt-react-class (aget js/MaterialUI "MenuItem")))
(def Menu (r/adapt-react-class (aget js/MaterialUI "Menu")))
(def Checkbox (r/adapt-react-class (aget js/MaterialUI "Checkbox")))
(def FormGroup (r/adapt-react-class (aget js/MaterialUI "FormGroup")))
(def FormLabel (r/adapt-react-class (aget js/MaterialUI "FormLabel")))
(def Backdrop (r/adapt-react-class (aget js/MaterialUI "Backdrop")))
(def Divider (r/adapt-react-class (aget js/MaterialUI "Divider")))
(def Breadcrumbs (r/adapt-react-class (aget js/MaterialUI "Breadcrumbs")))
(def List (r/adapt-react-class (aget js/MaterialUI "List")))
(def ListItem (r/adapt-react-class (aget js/MaterialUI "ListItem")))

