CREATE TABLE users
(user_id INT GENERATED ALWAYS AS IDENTITY,
 first_name VARCHAR(35) NOT NULL,
 last_name VARCHAR(35) NOT NULL,
 username VARCHAR(30) NOT NULL,
 email VARCHAR(100) NOT NULL,
 last_login TIMESTAMP,
 is_active BOOLEAN,
 password VARCHAR(255) NOT NULL,
 PRIMARY KEY(user_id)
 );
